# Generated by Django 5.2.14 on 2026-06-17 03:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [


        ''' crear la tabla BankMOvement con columnas '''
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('glosa', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),

        ''' crear la tabla Collection con columnas '''
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.IntegerField()),
                ('mes_cobro', models.DateField()),
                ('monto_cobro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('CLP', 'Peso chileno'), ('UF', 'Unidad fomento')], max_length=3)),
            ],
            options={
                'ordering': ['-mes_cobro'],
            },
        ),

        ''' crear la tabla BPayment con columnas '''
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abonado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bank_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tasks.bankmovement')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tasks.collection')),
            ],
            options={
                'unique_together': {('bank_movement', 'collection')},
            },
        ),
    ]
